trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  DeploymentDefaultLocation: 'swedencentral'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: Infrastructure/infrastructure.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType) -administratorLogin $(SqlAdminLogin) -administratorLoginPassword $(SqlAdminPassword)
